



desc MLT_1_Sample_WL900;



desc V_1_WL900_Sample_Login_Information;



select * from V_1_WL900_Sample_Login_Information order by SAMPLE_YEAR desc, SAMPLE_ID;



select count(*) from V_1_WL900_Sample_Login_Information;



select SAMPLE_YEAR, count(SAMPLE_YEAR) from V_1_WL900_Sample_Login_Information 
 group by SAMPLE_YEAR
 order by SAMPLE_YEAR desc
 ;




create or replace view V_1_WL900_Sample_Login_Information as 

select  
 SAMPLE_ID
,SAMPLE_YEAR
,SAMPLE_GROUP_ID
,DATE_RECEIVED
,STATUS_32767
,STATUS_SAMPLE
,STATUS_BILLING
,PROJECT_ID
,SUBMITTER_ID
,SAMPLE_FIELD_NBR
,SAMPLE_SAMPLED_BY
,SAMPLE_DATE_SAMPLED
,SAMPLE_NBR_OF_CONTAINERS
,SAMPLE_WITNESS
,SAMPLE_DATE_SHIPPED
,SAMPLE_QUANTITY
,SAMPLE_INTENDED_USE
,SAMPLE_TYPE
,SOURCE_NUMBER
,SOURCE_NAME
,SOURCE_LOCATION
,MATERIAL_DESCRIPTION
,MATERIAL_CONTRACTOR
,MATERIAL_INVOICE_NBR
,MATERIAL_SAMPLE_LOCATION
,MATERIAL_STATION
,MATERIAL_OFFSET_FROM_CENTER_LINE
,MATERIAL_MILEPOST
,MATERIAL_HOLE
,MATERIAL_DEPTH_OF_SAMPLE
,QLPAY_ID
,QLPAY_ITEM
,QLPAY_LOT
,QLPAY_SAMPLE_NBR
,RPT_CODE
,RPT_REQUESTED
,RPT_REFERRAL
,CERTIFICATION
,SHRP
,DATE_APPROVED
,DATE_BILLED
,DATES_TESTED
,DATE_TEST_BEGAN
,DATE_TEST_ENDED
,DATE_FINAL_REPORT
,CASE31
,CASE72
,CASE45
,CASE26
,CASE30
,CASE47
,CASE48
,CASE60
,REMARKS

from MLT_1_Sample_WL900
;
 








